[project]
name = "danish-dynaword"
version = "0.0.1"
description = "project code for the dfm datasheets."
readme = "README.md"
requires-python = ">=3.12,<3.13" # 3.13 have issues with spacy and pytorch
dependencies = [
    "tomlkit>=0.13.2", # reading toml
    # development
    "ipykernel>=6.29.5",
    "pip>=25.0.1",
    # test
    "pytest>=8.3.4",
    # formatting
    "ruff>=0.8.3",
    # new
]
